export class Urun {
    uid:string;
    key:string;
    urunadi:string;
    urunfiyat:number;
    oda:number;
    salon:number;
    banyo:number;
    brut:number;
    net:number;
    binayas:number;
    binakat:number;
    aidat:number;
    kira:string;
    adres:string;
    Takas:string;
    Site:string;
    Cephe:string;
    KullanimDurumu:string;
    YapiDurumu:string;
    Yakit:string;
    alan:string;
    Esya:string;
    Tapu:string;
    bulkat:string;
    aciklama:string;
    img:string;
    kayTarih: string;
    duzTarih: string;
}